### ISSUE TITLE
Possibly incorrect indexing of worldclim tiles

### ISSUE THREAD

**Issue by RRTogunov** [TheWangLab/algatr#23]
in [get_worldclim()](https://github.com/TheWangLab/algatr/blame/98501cf734e3bac5d9347fc8c26bd41120c34562/R/get_worldclim.R#L18C19-L18C19) function, raster defining worldclim tiles is 5x12 but I think should be 6:12. line should read:
` r <- terra::rast(vals = 1:72, nrows = 6, ncols = 12, ext = terra::ext(c(-180, 180, -90, 90)))
`
The following plot shows tile lon=0, lat = 0 over 5x12 60-cell grid shows misalignment of downloaded data
<img width="409" alt="image" src="https://github.com/TheWangLab/algatr/assets/20913113/0ce33875-47f5-4026-bde4-fa9833360e05">
in contrast to  following plot showing same tile plotted over 72-cell 6x12 grid:
<img width="410" alt="image" src="https://github.com/TheWangLab/algatr/assets/20913113/ee53aad9-6ced-4f9c-afd2-e06f4d6e01da">

code for reproducibility: 
 ``` r1 <- terra::rast(vals = 1:60, nrows = 5, ncols = 12, ext = terra::ext(c(-180, 180, -90, 90)))
  r2 <- terra::rast(vals = 1:72, nrows = 6, ncols = 12, ext = terra::ext(c(-180, 180, -90, 90)))
  wclim <- geodata::worldclim_tile(var = "bio", lon = 0, lat = 0, path = path)
  ggplot() + 
    tidyterra::geom_spatraster(data = r1) +
    tidyterra::geom_spatraster(data = wclim[[1]])
  ggplot() + 
    tidyterra::geom_spatraster(data = r2) +
    tidyterra::geom_spatraster(data = wclim[[1]])
    ```

**Comment by eachambers** [comment]
Hi-- you're right that there should be 6 rows, not 5 in the raster defined within get_worldclim(). I've now fixed this on the main branch. Thanks very much for bringing this to our attention!
