### ISSUE TITLE
rda - Error in eval(predvars, data, env) : object 'x' not found

### ISSUE THREAD

**Issue by renhamm** [TheWangLab/algatr#49]
I am unable to run any version of RDA without throwing the following error:
Error in eval(predvars, data, env) : object 'x' not found
<img width="256" alt="image" src="https://github.com/TheWangLab/algatr/assets/62153386/beda3886-07fe-4b42-a3dc-99076d2e5ce4">

This seems to be caused by an error with column names not matching somewhere within the call. I used the code found in the environmental data vingette to create all my files. I do however have to designate the "map" subsection of my env rasterPCA to run anything ("env <- raster::extract(env_pcs$map, coords)"). Could this be causing the issue?
If I try to create the env variable without desginating the map subsection I get this error:
<img width="619" alt="image" src="https://github.com/TheWangLab/algatr/assets/62153386/8a5a6665-b79e-4f21-9161-8bcb69d2993d">

Here are the first 5 lines of these files:
gen
<img width="463" alt="image" src="https://github.com/TheWangLab/algatr/assets/62153386/7d003e70-1de6-4c6a-b072-4f64ce4a62e7">
env
<img width="256" alt="image" src="https://github.com/TheWangLab/algatr/assets/62153386/60d19287-8105-4790-a067-668750ae2d20">

**Comment by renhamm** [comment]
Additionally, when I try to run the rda_varpart function, it runs for many hours until failing at a later step with the same "Error in eval(predvars, data, env) : object 'x' not found" error. See below


Step: R2.adj= 0 
Call: gen ~ 1 
 
                R2.adjusted
<All variables> 0.167178052
+ PC1           0.059566847
+ PC3           0.051385898
+ PC6           0.040925515
+ PC2           0.039529809
+ PC4           0.039227137
+ PC7           0.035972602
+ PC11          0.032235961
+ PC5           0.030131642
+ PC10          0.021734464
+ PC9           0.017398951
+ PC8           0.014242854
+ PC14          0.013549741
+ PC17          0.010620614
+ PC15          0.009026529
+ PC16          0.007936154
+ PC18          0.007544987
+ PC12          0.006530425
+ PC13          0.006452205
+ PC19          0.002516495
<none>          0.000000000

      Df    AIC      F Pr(>F)   
+ PC1  1 3232.3 21.649  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.05956685 
Call: gen ~ PC1 
 
                R2.adjusted
<All variables>  0.16717805
+ PC10           0.07974282
+ PC8            0.07514836
+ PC7            0.07512217
+ PC3            0.07424076
+ PC2            0.07317998
+ PC6            0.07301140
+ PC9            0.06980025
+ PC15           0.06908068
+ PC18           0.06890552
+ PC11           0.06868092
+ PC12           0.06832281
+ PC4            0.06797327
+ PC5            0.06721863
+ PC17           0.06642349
+ PC14           0.06584432
+ PC16           0.06351185
+ PC13           0.06284409
+ PC19           0.06213360
<none>           0.05956685

       Df    AIC      F Pr(>F)   
+ PC10  1 3226.2 8.1254  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.07974282 
Call: gen ~ PC1 + PC10 
 
                R2.adjusted
<All variables>  0.16717805
+ PC8            0.09293808
+ PC7            0.09159595
+ PC3            0.08954178
+ PC15           0.08862148
+ PC4            0.08860542
+ PC9            0.08823516
+ PC6            0.08792074
+ PC5            0.08787182
+ PC12           0.08760820
+ PC18           0.08757385
+ PC14           0.08642175
+ PC2            0.08635651
+ PC17           0.08598522
+ PC11           0.08521532
+ PC16           0.08387813
+ PC13           0.08360862
+ PC19           0.08233665
<none>           0.07974282

      Df    AIC      F Pr(>F)   
+ PC8  1 3222.5 5.7133  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.09293808 
Call: gen ~ PC1 + PC10 + PC8 
 
                R2.adjusted
<All variables>  0.16717805
+ PC4            0.10264448
+ PC7            0.10227220
+ PC3            0.10198777
+ PC18           0.10167804
+ PC9            0.10141387
+ PC15           0.10122231
+ PC12           0.10094628
+ PC5            0.09998569
+ PC14           0.09988455
+ PC2            0.09922421
+ PC17           0.09919715
+ PC6            0.09870221
+ PC11           0.09819950
+ PC16           0.09737812
+ PC13           0.09636665
+ PC19           0.09555252
<none>           0.09293808

      Df  AIC      F Pr(>F)   
+ PC4  1 3220 4.4938  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.1026445 
Call: gen ~ PC1 + PC10 + PC8 + PC4 
 
                R2.adjusted
<All variables>   0.1671781
+ PC12            0.1109465
+ PC18            0.1107006
+ PC9             0.1105365
+ PC15            0.1103054
+ PC7             0.1101770
+ PC5             0.1091507
+ PC6             0.1087637
+ PC14            0.1086860
+ PC17            0.1081339
+ PC11            0.1078317
+ PC3             0.1076225
+ PC2             0.1075317
+ PC16            0.1065382
+ PC13            0.1061206
+ PC19            0.1053729
<none>            0.1026445

       Df    AIC      F Pr(>F)   
+ PC12  1 3217.9 4.0069  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.1109465 
Call: gen ~ PC1 + PC10 + PC8 + PC4 + PC12 
 
                R2.adjusted
<All variables>   0.1671781
+ PC7             0.1192458
+ PC9             0.1188585
+ PC15            0.1179492
+ PC18            0.1168212
+ PC14            0.1166633
+ PC5             0.1164493
+ PC17            0.1163041
+ PC3             0.1162360
+ PC11            0.1159763
+ PC2             0.1150834
+ PC16            0.1149893
+ PC6             0.1144412
+ PC19            0.1136961
+ PC13            0.1134949
<none>            0.1109465

      Df    AIC      F Pr(>F)   
+ PC7  1 3215.8 4.0247  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.1192458 
Call: gen ~ PC1 + PC10 + PC8 + PC4 + PC12 + PC7 
 
                R2.adjusted
<All variables>   0.1671781
+ PC18            0.1251941
+ PC14            0.1250208
+ PC5             0.1242736
+ PC11            0.1242705
+ PC3             0.1241077
+ PC15            0.1240180
+ PC9             0.1239345
+ PC17            0.1232763
+ PC2             0.1232147
+ PC16            0.1230242
+ PC6             0.1225620
+ PC19            0.1219968
+ PC13            0.1219931
<none>            0.1192458

       Df    AIC      F Pr(>F)   
+ PC18  1 3214.6 3.1759  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.1251941 
Call: gen ~ PC1 + PC10 + PC8 + PC4 + PC12 + PC7 + PC18 
 
                R2.adjusted
<All variables>   0.1671781
+ PC14            0.1303672
+ PC5             0.1301860
+ PC3             0.1300970
+ PC11            0.1293536
+ PC17            0.1292695
+ PC16            0.1291788
+ PC15            0.1289616
+ PC2             0.1287767
+ PC9             0.1287498
+ PC6             0.1284402
+ PC13            0.1279696
+ PC19            0.1279007
<none>            0.1251941

       Df    AIC      F Pr(>F)   
+ PC14  1 3213.6 2.8976  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.1303672 
Call: gen ~ PC1 + PC10 + PC8 + PC4 + PC12 + PC7 + PC18 + PC14 
 
                R2.adjusted
<All variables>   0.1671781
+ PC3             0.1353140
+ PC5             0.1352816
+ PC16            0.1345269
+ PC11            0.1343445
+ PC17            0.1342844
+ PC15            0.1342832
+ PC2             0.1341881
+ PC9             0.1340273
+ PC6             0.1338031
+ PC13            0.1334009
+ PC19            0.1330112
<none>            0.1303672

      Df    AIC      F Pr(>F)   
+ PC3  1 3212.7 2.8192  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.135314 
Call: gen ~ PC1 + PC10 + PC8 + PC4 + PC12 + PC7 + PC18 + PC14 + PC3 
 
                R2.adjusted
<All variables>   0.1671781
+ PC5             0.1399860
+ PC16            0.1394572
+ PC11            0.1393526
+ PC17            0.1392522
+ PC15            0.1391476
+ PC2             0.1389647
+ PC6             0.1389435
+ PC9             0.1386971
+ PC13            0.1383680
+ PC19            0.1380016
<none>            0.1353140

      Df    AIC      F Pr(>F)   
+ PC5  1 3211.9 2.7221  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.139986 
Call: gen ~ PC1 + PC10 + PC8 + PC4 + PC12 + PC7 + PC18 + PC14 + PC3 +      PC5 
 
                R2.adjusted
<All variables>   0.1671781
+ PC16            0.1440444
+ PC17            0.1439926
+ PC6             0.1438940
+ PC2             0.1438696
+ PC11            0.1437417
+ PC15            0.1434962
+ PC9             0.1429353
+ PC19            0.1426975
+ PC13            0.1426489
<none>            0.1399860

       Df    AIC      F Pr(>F)   
+ PC16  1 3211.3 2.4983  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.1440444 
Call: gen ~ PC1 + PC10 + PC8 + PC4 + PC12 + PC7 + PC18 + PC14 + PC3 +      PC5 + PC16 
 
                R2.adjusted
<All variables>   0.1671781
+ PC17            0.1480835
+ PC2             0.1480465
+ PC6             0.1479245
+ PC11            0.1477882
+ PC15            0.1475619
+ PC9             0.1471481
+ PC13            0.1468240
+ PC19            0.1466270
<none>            0.1440444

       Df    AIC      F Pr(>F)   
+ PC17  1 3210.8 2.4934  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.1480835 
Call: gen ~ PC1 + PC10 + PC8 + PC4 + PC12 + PC7 + PC18 + PC14 + PC3 +      PC5 + PC16 + PC17 
 
                R2.adjusted
<All variables>   0.1671781
+ PC2             0.1516865
+ PC6             0.1516593
+ PC15            0.1516077
+ PC11            0.1514127
+ PC9             0.1511911
+ PC13            0.1510439
+ PC19            0.1503827
<none>            0.1480835

      Df    AIC      F Pr(>F)   
+ PC2  1 3210.3 2.3336  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.1516865 
Call: gen ~ PC1 + PC10 + PC8 + PC4 + PC12 + PC7 + PC18 + PC14 + PC3 +      PC5 + PC16 + PC17 + PC2 
 
                R2.adjusted
<All variables>   0.1671781
+ PC9             0.1549365
+ PC15            0.1549018
+ PC11            0.1548049
+ PC13            0.1545023
+ PC6             0.1542060
+ PC19            0.1539890
<none>            0.1516865

      Df  AIC      F Pr(>F)   
+ PC9  1 3210 2.2038  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.1549365 
Call: gen ~ PC1 + PC10 + PC8 + PC4 + PC12 + PC7 + PC18 + PC14 + PC3 +      PC5 + PC16 + PC17 + PC2 + PC9 
 
                R2.adjusted
<All variables>   0.1671781
+ PC15            0.1578348
+ PC13            0.1577716
+ PC11            0.1576579
+ PC19            0.1572350
+ PC6             0.1568031
<none>            0.1549365

       Df    AIC      F Pr(>F)   
+ PC15  1 3209.8 2.0738  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.1578348 
Call: gen ~ PC1 + PC10 + PC8 + PC4 + PC12 + PC7 + PC18 + PC14 + PC3 +      PC5 + PC16 + PC17 + PC2 + PC9 + PC15 
 
                R2.adjusted
<All variables>   0.1671781
+ PC13            0.1606866
+ PC11            0.1604793
+ PC19            0.1601606
+ PC6             0.1597520
<none>            0.1578348

       Df    AIC      F Pr(>F)   
+ PC13  1 3209.7 2.0567  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.1606866 
Call: gen ~ PC1 + PC10 + PC8 + PC4 + PC12 + PC7 + PC18 + PC14 + PC3 +      PC5 + PC16 + PC17 + PC2 + PC9 + PC15 + PC13 
 
                R2.adjusted
<All variables>   0.1671781
+ PC11            0.1631435
+ PC19            0.1628521
+ PC6             0.1625960
<none>            0.1606866

       Df    AIC      F Pr(>F)   
+ PC11  1 3209.7 1.9101  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.1631435 
Call: gen ~ PC1 + PC10 + PC8 + PC4 + PC12 + PC7 + PC18 + PC14 + PC3 +      PC5 + PC16 + PC17 + PC2 + PC9 + PC15 + PC13 + PC11 
 
                R2.adjusted
<All variables>   0.1671781
+ PC19            0.1652651
+ PC6             0.1650437
<none>            0.1631435

       Df    AIC      F Pr(>F)   
+ PC19  1 3209.8 1.7853  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.1652651 
Call: gen ~ PC1 + PC10 + PC8 + PC4 + PC12 + PC7 + PC18 + PC14 + PC3 +      PC5 + PC16 + PC17 + PC2 + PC9 + PC15 + PC13 + PC11 + PC19 
 
                R2.adjusted
<All variables>   0.1671781
+ PC6             0.1671781
<none>            0.1652651

      Df  AIC      F Pr(>F)   
+ PC6  1 3210 1.7075  0.002 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Step: R2.adj= 0.1671781 
Call: gen ~ PC1 + PC10 + PC8 + PC4 + PC12 + PC7 + PC18 + PC14 + PC3 +      PC5 + PC16 + PC17 + PC2 + PC9 + PC15 + PC13 + PC11 + PC19 +      PC6

**Comment by eachambers** [comment]
Hi, this error likely resulted from your coordinates object not having the column names x and y. We've now fixed this so please go ahead and re-install the package and let us know if the error still occurs.

Anne

**Comment by renhamm** [comment]
That error isn't thrown any more, but I am still unable to properly run the mod_prd_gs call. There isn''t any r2 outputted for only this call. See below a direct comparison between mod_prd_geo and mod_prd_gs.
<img width="420" alt="image" src="https://github.com/TheWangLab/algatr/assets/62153386/647b3b1c-84f6-474c-a5de-be7a5d8b9fe4">
<img width="168" alt="image" src="https://github.com/TheWangLab/algatr/assets/62153386/493cca8b-9e7f-48f9-bd26-a9bf2cb61932">

Does this still have something to do with the x/y naming?

**Comment by eachambers** [comment]
#51

**Comment by eachambers** [comment]
Hi, the reason for this was that your environmental variables have the same names as the PCs when the partial RDA was run with `correctPC = TRUE` (i.e., correcting for population structure using a PCA). You can see this in the variable names of your call for `mod_pRDA_gs`: the predictor variables are named PC1, PC2, and PC3, and the conditioning variables are also named PC1, PC2, and PC3.

We have fixed our code to accommodate cases in which environmental variables are named PC1, PC2, etc., but it's worth mentioning that it's always best to be specific when naming your environmental variables. For example, in the vignettes, the enviro PCs are named CA_rPCA1, CA_rPCA2, and CA_rPCA3.

Once again, be sure to re-install the package and try again and let us know if the problem persists. Thanks.

Anne
