### ISSUE TITLE
Issue with kriging and mapping Q values

### ISSUE THREAD

**Issue by RowanLymbery** [TheWangLab/algatr#53]
Hi Anne and Anusha,

Thanks so much for producing the algatr package - it's an amazing resource for landscape geneticists, particularly those such as me who are fairly new to spatial analysis of genetic variation!

I've been running genetic structure analyses with TESS folowing the algatr vignette, and have run into an error with trying to krige and map the Q-values across the landscape. The 'tess_ktest()' function runs as expected, with best k=4 and q-matrix extracted as expected:

> head(qmat_libfilt_nodups)
                V1         V2        V3         V4
G356781 0.01859810 0.14887390 0.7961264 0.03640166
G356784 0.18413187 0.44738837 0.3006662 0.06781356
G356792 0.01325051 0.14315294 0.8119810 0.03161552
G356800 0.08738253 0.06700812 0.1748154 0.67079396
G356815 0.14735428 0.54849574 0.2471872 0.05696281
G356819 0.06099799 0.08457345 0.0659272 0.78850135

I have raster layers for mapping the Q values; e.g. I've been using:
> krig_raster
class       : SpatRaster 
dimensions  : 101, 82, 1  (nrow, ncol, nlyr)
resolution  : 6000, 6000  (x, y)
extent      : 306000, 798000, 6111000, 6717000  (xmin, xmax, ymin, ymax)
coord. ref. : GDA94 / MGA zone 50 (EPSG:28350) 
source(s)   : memory
name        :     Bio13 
min value   :  32.43384 
max value   : 229.79206 

And coordinates for the samples in the same order as the q-matrix, as a spatial points object with the same CRS as the raster:
> pts_sp
class       : SpatialPoints 
features    : 82 
extent      : 399287, 814035.1, 6210875, 6530356  (xmin, xmax, ymin, ymax)
crs         : +proj=utm +zone=50 +south +ellps=GRS80 +units=m +no_defs 

However, when I run 'tesskrig()' with these outputs, I get warnings of singular covariance matrix:
> krig_admix <- tess_krig(qmat_libfilt_nodups, pts_sp, krig_raster)
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In predict.gstat(g, newdata = newdata, block = block,  ... :
  Covariance matrix singular at location [309000,6.714e+06,0]: skipping...
2: In predict.gstat(g, newdata = newdata, block = block,  ... :
  Covariance matrix singular at location [315000,6.714e+06,0]: skipping...

Looking at the resulting krig_admix SpatRaster, it has only interpolated values for one cluster (k3), the others have produced NAs:
> krig_admix
class       : SpatRaster 
dimensions  : 101, 82, 4  (nrow, ncol, nlyr)
resolution  : 6000, 6000  (x, y)
extent      : 306000, 798000, 6111000, 6717000  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=50 +south +ellps=GRS80 +units=m +no_defs 
source(s)   : memory
names       :  K1,  K2,         K3,  K4 
min values  : NaN, NaN, 0.03568737, NaN 
max values  : NaN, NaN, 0.92460640, NaN

And when plotted with tess_ggplot only one cluster is mapped.
![Rplot](https://github.com/TheWangLab/algatr/assets/49020168/a71a9e19-e854-4c63-87c5-5709dbbb8602)

Initially I thought the singular covariance matrix was due to duplicate coordinates, but I've removed all the duplicates and the issue hasn't resolved (the above qmatrix and coordinates are with location duplicates removed). I've tried different raster layers in case it was an issue with the grid, but get the same result. And the qmatrix works when mapping clusters with the default tess3r functions - I'm just keen to use the algatr alternatives because I really like the mapping options as highlighted in the vignette examples!

Do you have any thoughts on why the krig function is only returning values for one of the clusters? Apologies that I haven't included a full reproducible example here - it seems the answer might be related to the specific inputs I'm using - but if you need me to provide more details/data please let me know.

Many thanks,
Rowan

**Comment by eachambers** [comment]
Hi Rowan,

Thanks for getting in touch and for providing so much information. Would you be able to send us a couple additional things for us to troubleshoot: (1) The structure-style bar plot of your individuals' assignment into the four different clusters, and (2) the map produced using the default tess3r plotting functions?

I suspect the problem might be coming from the fact that there may be a singular (or no) fit of the kriging model which would explain why the map looks the way it does, or that there is little variation in Q values at the other clusters.

Anne

**Comment by RowanLymbery** [comment]
Hi Anne,

Thanks very much for your reply! I've been working more on these data with some colleagues yesterday and today, and was about to post an update on this thread myself. We tried projecting the coords to the correct CRS as a matrix (rather than an sp object), using (env$Veg is equivalent to krig_raster above)
>coords_t_utm<-terra::project(as.matrix(tess_coords_libfilt), from="+proj=longlat + dataum=WGS84",   to=crs(env$Veg)) 
> head(coords_t_utm)
         [,1]    [,2]
[1,] 425687.8 6481908
[2,] 440114.8 6360976
[3,] 440114.8 6360976
[4,] 440114.8 6360976
[5,] 426645.9 6503194
[6,] 426645.9 6503194

And now the tess_krig function seems to produce the expected output!
>krig<-tess_krig(tess_qmat_libfilt, coords_t_utm, ras_grid)
> krig
class       : SpatRaster 
dimensions  : 202, 164, 4  (nrow, ncol, nlyr)
resolution  : 3000, 3000  (x, y)
extent      : 306000, 798000, 6111000, 6717000  (xmin, xmax, ymin, ymax)
coord. ref. :  
source(s)   : memory
names       :        K1,        K2,        K3,         K4 
min values  : 0.0000000, 0.0000000, 0.0000000, 0.03033997 
max values  : 0.7977171, 0.5697944, 0.8363201, 0.80070618 

maxQ_plot <- tess_ggplot(krig, plot_method="maxQ")
![image](https://github.com/TheWangLab/algatr/assets/49020168/84cec2a8-e9a4-4f9c-85ba-636e63c65bf0)

Thus map has similar cluster boundaries to the default tess3 map, so interpolation seems to be working as expected given the qmatrix. Out of interest too, the admixture plot showed reasonable variation in cluster assignment among samples (apologies for the non-matching colours:
![image](https://github.com/TheWangLab/algatr/assets/49020168/50b5bfbd-990c-425d-b2e3-49232c1b0b53)

So I think it must have been an issue with my original CRS projection for the coords, or using the sp format?

Many thanks,
Rowan

**Comment by RowanLymbery** [comment]
(Meant to say, I'm happy for this issue to be closed - I just thought the above extra info might be of interest/relevant in case anyone else tries to do the same thing I did)

**Comment by eachambers** [comment]
Hi Rowan,

Thanks for your thorough response and for solving the issue! You certainly do want the data to be projected (i.e., not just lat/long values) for kriging.

All the best,
Anne
