### ISSUE TITLE
How to prepare the input file: CA_env ?

### ISSUE THREAD

**Issue by yangwukaidi** [TheWangLab/algatr#68]
I'd like to try to use this tool. But I don't quite understand how to prepare for the input file (CA_env).
Can you help me?
Thanks.

**Comment by eachambers** [comment]
Thanks for reaching out. The `CA_env` object is the top three PCs resulting from performing a raster PC on 19 bioclimatic variables (obtained from the World Clim database) across the state of California. This is described [here](https://github.com/TheWangLab/algatr/tree/main?tab=readme-ov-file#the-example-dataset).

The environmental data processing vignette (available [here](https://github.com/TheWangLab/algatr/blob/main/vignettes/enviro_data_vignette.Rmd#L158)) walks through the steps required to perform a raster PCA; specifically, take a look at how we've generated the `env_pcs` object in this vignette. Let me know if you have any further questions.

Thanks,
Anne
