### ISSUE TITLE
gdm_format function not found

### ISSUE THREAD

**Issue by ioanaanghel** [TheWangLab/algatr#71]
Hello, 

When running the following line, I get an error that the function doesn't exist. 
`gdm_format(euc_dists2, lipa_coords2, env_pcs2$map, scale_gendist = TRUE)`

> Error in gdm_format(euc_dists2, lipa_coords2, env) : 
could not find function "gdm_format"

Other GDM functions work. I tried to reinstall algatr but that also did not fix the issue. 
Do you have any suggestions?

Thank you for your help!

**Comment by AnushaPB** [comment]
Hello! I can't seem to reproduce your error on my end. Did you restart your R session/reload the algatr library after you reinstalled algatr? Maybe try reinstalling again and confirm that the reinstall was successful?
