### ISSUE TITLE
lfmm input format

### ISSUE THREAD

**Issue by WWz33** [TheWangLab/algatr#73]
Hi TheWangLab!
What confuses me is that I found that many published [articles'](https://doi.org/10.1093/molbev/msae130) [public](https://github.com/marcabeer/stquoll_landscape_genomics/blob/main/analyses/gea_tests/lfmm/lfmm.R) [codes](https://github.com/TannerMyers/distichus-population-genomics/blob/66a87df59d483a9b66a2b117d1f2be3c508e0c76/spatial-variation/scripts/within-east-LFMM.r#L8) use `lfmm format` as **lfmm2** input not `genotype dosage matrix.` 
I also tried emailing the author of lfmm2 to understand this issue, but I didn't get a reply.

I appreciate your input and await your response.
Best!

**Comment by eachambers** [comment]
Hi,

Apologies for the late response! The LFMM format is the same as a genotype dosage matrix: individuals are rows and each SNP is a column in the matrix. In the example code you sent me, the `imputed_geno` object is the same as the `gen` object made [here](https://github.com/TheWangLab/algatr/blob/main/vignettes/LFMM_vignette.Rmd#L59) in the algatr LFMM vignette (except that there are no row or column names in `imputed_geno` like there are in `gen`). You can confirm this by looking at the functions that run the method in the lfmm package documentation (e.g., for the `lfmm_ridge()` function): they require a "response variable matrix" of genotypes, not any particular LFMM-type file.

So, if you have an LFMM-type file, you should be able to read it into R using LEA's `read.lfmm()` function (as the authors do in the link you sent over), and then you can proceed to use algatr as normal!

Let me know if you have any other questions.

Best,
Anne

**Comment by WWz33** [comment]
Hi,Anne 

Thank you very much for your answer, it helped me a lot!
When I use this function, no matter I use the vcf generated by `Beagle imputa` or `plink --recode vcf-iid`, this error will be shown.
I can only import `vcfR objects`
```
test1 <- vcf_to_dosage("test.vcf")
Error in x@fix : 
  no applicable method for `@` applied to an object of class "character"
```

Best!

**Comment by eachambers** [comment]
Hi,

Thanks for pointing this out-- this is something we missed adding to the `vcf_to_dosage()` function. I've just fixed it so if you go ahead and re-install the package, you should be able to use the function on a path to a vcf file now.

Anne

**Comment by WWz33** [comment]
Hi,Anne

Thank you very much for your answers.
I also have a doubt that `tess3r` can call multi-threads, but I see that this option is not available in the package

Best!

**Comment by eachambers** [comment]
Hi,

You're right that we didn't code the `openMP.core.num` arg that the `tess3()` function uses for multithreading into `tess_ktest()` (or `tess_do_everything()`). I'd suggest just running `tess3()` directly as we do in the vignette [here](https://github.com/TheWangLab/algatr/blob/main/vignettes/TESS_vignette.Rmd#L130); that way you could specify that argument and the rest can be done within algatr. You could also copy the `tess_ktest()` function within your own environment and modify the line [here ](https://github.com/TheWangLab/algatr/blob/main/R/TESS.R#L150) that runs TESS to add that argument.

Good luck!

Anne

**Comment by WWz33** [comment]
Hi,Anne

Thanks for the answer, I think you've done a great job of integrating the landscape genome packages.
 I'm going to use it heavily in a while. If you have any questions, I will give you positive feedback and I would love you to answer them.

Best!
