### ISSUE TITLE
gen_dist with type "pc" @ cannot be applied to a matrix

### ISSUE THREAD

**Issue by alexkrohn** [TheWangLab/algatr#87]
Hi there,

First off, I really want to congratulate you all on an excellent package that ties together important pop gen and landscape genetic programs in a well-documented, easy to use framework. Serious kudos!

I'm getting an error that is stopping me from running `mmrr`. 

```
vcf <- "mod_163inds-75maxmissing-biallelic.recode.vcf"

str_dosage <- str_impute(vcf, K = 3)

pc_gen_dist <- gen_dist(str_dosage, dist_type = "pc", npc_selection = "auto", criticalpoint = 2.0234)
```
Results in error `Error in x@fix : 
  no applicable method for `@` applied to an object of class "matrix"`

This same error occurs when `type = 'bray_curtis'`

However, euclidean distances can be calculated without a problem. 
```
euc_gen_dist <- gen_dist(str_dosage, dist_type="euclidean")
```

Any idea what might cause that error? I assume it's something with my VCF and not a bug.

... For what it's worth, even `mmrr_run` fails with the euclidean matrix (`Error in colMeans(x, na.rm = TRUE) : 'x' must be numeric`) but I assume that's an unrelated issue that I'll have to tackle later. (Running `apply(euc_gen_dist, 1, class)` over rows or columns, or `lapply(env_matrices, function(x) apply(x, 1, class))` over rows or columns also shows all values as numeric.)

**Comment by AnushaPB** [comment]
Hi! Thanks for reaching out. I have tried to replicate your error on my end by running:

```
library(algatr)

load_algatr_example()

str_dosage <- str_impute(liz_vcf, K = 3)

pc_gen_dist <- gen_dist(str_dosage, dist_type = "pc", npc_selection = "auto", criticalpoint = 2.0234)
```
But, I do not get an error. Can you confirm this does not return an error on your end? Could you also try reinstalling algatr (we have made some recent updates that might fix the latter error)?

Can you also send me a bit more info about your `str_dosage` (e.g. the outputs of class(str_dosage), str(str_dosage), and str_dosage[1:10, 1:10])?

**Comment by alexkrohn** [comment]
Wow! Interesting. Seems like it was an error with an outdated package. At first, I got the same error as above even with the example data. After re-installing `algatr`, updating all packages, and restarting R, it worked both on the test data and on my data. 

Apologies for the seemingly silly issue, but it is resolved now. Happy new year to y'all!
